name = "vibe/p2p-lending"
version = "0.0.0"
compiler = "v1.1.2"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'vibe/p2p-lending'"

[repository]
user = "vibe"
project = "p2p-lending"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
